# Generated by Django 2.2.4 on 2019-09-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_auto_20190826_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotransaccion',
            name='abono',
            field=models.BooleanField(default=True),
        ),
    ]
