# Generated by Django 2.2.4 on 2019-08-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.PositiveSmallIntegerField(choices=[(1, 'cliente'), (2, 'empleado'), (3, 'admin')], default=1),
            preserve_default=False,
        ),
    ]
